language: java

jdk:
- oraclejdk8

install:
- ./mvnw install -Dmaven.test.skip=true

script:
- ./mvnw test -DactiveProfile=test
after_success:
- ./mvnw clean test -DactiveProfile=test jacoco:report coveralls:report
notifications:
  email:
  - heyuxian.me@gmail.com